### ISSUE TITLE
From Golden Combs - Ceramic Hive Break/Replace Crash

### ISSUE THREAD

**Issue by kittendoll** [Aetherial-Labs/Issue-Reporting#1]
With a hibernating populated ceramic hive with a honey pot atop it, while using a pickaxe to 'break' the brood pot allows both brood pot and honey pot to be collected as items in the appropriate slots (inventory for honeypot, backpack slot for the brood pot) on placing the brood pot back down on the ground it enters a corrupted state in which any player who looks directly at it will crash to desktop.

The server I was playing on was able to recover by deleting the affected block without looking at it, the admin then verified the process on a test save that at least in a copy of our world the process happened any time a populated brood pot was pickaxe-broken and then placed again.

**Comment by kittendoll** [comment]
Did some further testing: it does not happen in creative mode! In creative mode the breaking the brood pot results in an empty brood pot that can be placed again with no issue.  In a new creative mode world that has a hive placed and populated, then switched to survival mode, and only THEN breaking the brood pot with the pickaxe, the error reocurrs as before with the following log. HOWEVER: the linked files the error report says should be there are not to be found on my harddrive, which is a bit weird.

Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.17.11 (Stable)
17-04-23 5:57:26 PM: Critical error occurred in the following mod: fromgoldencombs@1.3.15
Loaded Mods: cralutweaks@1.0.2, RelightTorches@1.0.0, visibleore@1.0.1, game@1.17.11, fromgoldencombs@1.3.15, hudclock@2.8.0, playercorpse@1.5.5, prospectorinfo@4.1.4, creative@1.17.11, survival@1.17.11, metalrecovery@0.1.18-rc.2, campaigncartographer@3.1.2, knapster@2.3.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at FromGoldenCombs.BlockEntities.BECeramicBroodPot.GetBlockInfo(IPlayer forPlayer, StringBuilder dsc)
   at Vintagestory.API.Common.Block.GetPlacedBlockInfo(IWorldAccessor world, BlockPos pos, IPlayer forPlayer) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 2150
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.ComposeBlockInfoHud() in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockAndEntityInfo.cs:line 57
   at Vintagestory.Client.NoObf.HudElementBlockAndEntityInfo.BlockInView() in VintagestoryLib\Client\Systems\Gui\Huds\HudElementBlockAndEntityInfo.cs:line 190
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 105
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1196
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 1103
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 123
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 678
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 622
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 124
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 16-04-23 8:08:23 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2186699272363415476, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.11.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\kitty\AppData\Local\Temp\RDR46AD.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER46BE.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER46CF.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER46DC.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER470C.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 36bc81d9-4509-4ddf-89a0-f9e1605110e6
Report Status: 268435456
Hashed bucket: 0215b19e9f6a6c1d1e58b7670fd397b4
Cab Guid: 0 }
--------------
{ TimeGenerated = 17-03-23 9:01:45 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2186699272363415476, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.11.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\kitty\AppData\Local\Temp\RDR337D.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER338E.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER338F.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER33A9.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER33C9.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 21fd2632-6eed-4118-a37d-d9412235ffac
Report Status: 268435456
Hashed bucket: 0215b19e9f6a6c1d1e58b7670fd397b4
Cab Guid: 0 }

**Comment by VinterNacht** [comment]
I will try to look into this.  I cannot recreate it on 1.18; I suspect this may be a lingering 1.17 bug caused by a little issue I ran into when updating it.

**Comment by kittendoll** [comment]
So, here's the save file of the creative world that's crashing on following the steps.
[gloomy superflat world.zip](https://github.com/Aetherial-Labs/Issue-Reporting/files/11266646/gloomy.superflat.world.zip)

**Comment by VinterNacht** [comment]
Part of the issue is that I have to necromantically rebirth that 1.17 code.  It got lost for reasons.  (Namely -> I've upgraded my PC since then and lost the old code because I didn't put it on GitHub for... Reasons?)

Will fix ASAP.

**Comment by VinterNacht** [comment]
Can you confirm this is still an issue?

**Comment by kittendoll** [comment]
I cannot confirm it, as with a fresh install of 1.18 and the newest FGC
(the server i play on is on hiatus), i crash on attempt to load into a
creative world every time to test it. log as follows:

Running on 64 bit Windows with 16 GB RAM
Game Version: v1.18.6 (Stable)
08-07-23 12:56:05 PM: Critical error occurred in the following mod:
***@***.***
Loaded Mods: ***@***.***, ***@***.***, ***@***.***,
***@***.***, ***@***.***, ***@***.***,
***@***.***, ***@***.***, ***@***.***
System.MissingFieldException: Field not found:
'Vintagestory.API.Common.Entities.Entity.Pos'.
   at
hudclock.src.ui.ClaimAreaDialog.RequestClaimInfoOfPlayerPosition(Single
gameTick)
   at hudclock.src.ui.ClaimAreaDialog.Build()
   at hudclock.src.busineslogic.ClaimDialogController..ctor(ICoreClientAPI
clientApi, ClockModSettingsController clockModSettingsController)
   at hudlock.src.HUDClockMod.PlayerReady(EnumHandling& handling)
   at Vintagestory.Client.NoObf.ClientEventAPI.TriggerIsPlayerReady() in
VintagestoryLib\Client\API\ClientEventAPI.cs:line 379
   at
Vintagestory.Client.NoObf.GeneralPacketHandler.HandlePlayerData(Packet_Server
packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 314
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single
deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 747
   at
Vintagestory.Client.GuiScreenConnectingToServer.RenderToDefaultFramebuffer(Single
dt) in
VintagestoryLib\Client\MainMenu\Screens\GuiScreenConnectingToServer.cs:line
305
   at Vintagestory.Client.ScreenManager.Render(Single dt) in
VintagestoryLib\Client\ScreenManager.cs:line 724
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in
VintagestoryLib\Client\ScreenManager.cs:line 627
   at
Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object
sender, FrameEventArgs e) in
VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 126
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in
C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double
frames_per_second) in
C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args,
String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in
VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by kittendoll** [comment]
On a second reinstall, the creative world loads and the bug no longer
manifests.

**Comment by VinterNacht** [comment]
I just doublechecked all of this on my live build, and can confirm the bug does not seem to persist.
