### ISSUE TITLE
Game crashing when opening the Handbook Apiculture 101 on 1.8.8 Net7 Version

### ISSUE THREAD

**Issue by frankuck99** [Aetherial-Labs/Issue-Reporting#15]
Crashlog:

Running on 64 bit Windows with 32535 MB RAM
Game Version: v1.18.8 (Stable)
15/8/2023 15:52:07: Critical error occurred
Loaded Mods: aculinaryartillery@1.0.14, game@1.18.8, fromgoldencombs@1.4.20, hudclock@3.2.1, claywheel@1.1.0, prospectorinfo@4.3.0, creative@1.18.8, survival@1.18.8, knapster@2.4.2
System.ArgumentNullException: Value cannot be null. (Parameter 'Asset Data is null. Is the asset loaded?')
   at Vintagestory.Client.NoObf.SvgLoader.rasterizeSvg(IAsset svgAsset, Int32 textureWidth, Int32 textureHeight, Int32 width, Int32 height, Nullable`1 color) in VintagestoryLib\Client\ClientPlatform\SvgLoader.cs:line 154
   at Vintagestory.Client.NoObf.SvgLoader.DrawSvg(IAsset svgAsset, ImageSurface intoSurface, Matrix matrix, Int32 posx, Int32 posy, Int32 width, Int32 height, Nullable`1 color) in VintagestoryLib\Client\ClientPlatform\SvgLoader.cs:line 74
   at Vintagestory.Client.NoObf.GuiAPI.DrawSvg(IAsset svgAsset, ImageSurface intoSurface, Matrix matrix, Int32 posx, Int32 posy, Int32 width, Int32 height, Nullable`1 color) in VintagestoryLib\Client\API\GuiAPI.cs:line 63
   at Vintagestory.GameContent.WaypointMapLayer.<>c__DisplayClass18_1.<.ctor>b__2(Context ctx, Int32 x, Int32 y, Single w, Single h, Double[] rgba) in VSEssentials\Systems\WorldMap\WaypointLayer\WaypointMapLayer.cs:line 119
   at Vintagestory.API.Client.IconUtil.DrawIconInt(Context cr, String type, Int32 x, Int32 y, Single width, Single height, Double[] rgba) in VintagestoryApi\Client\UI\IconUtil.cs:line 96
   at Vintagestory.API.Client.IconUtil.DrawIcon(Context cr, String type, Double x, Double y, Double width, Double height, Double[] rgba) in VintagestoryApi\Client\UI\IconUtil.cs:line 79
   at Vintagestory.API.Client.IconComponent.ComposeElements(Context ctx, ImageSurface surface) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\IconComponent.cs:line 48
   at Vintagestory.API.Client.GuiElementRichtext.ComposeFor(ElementBounds bounds, Context ctx, ImageSurface surface) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:line 421
   at Vintagestory.API.Client.GuiElementRichtext.Compose(Boolean genTextureLater) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:line 128
   at Vintagestory.API.Client.GuiComposer.Compose(Boolean focusFirstElement) in VintagestoryApi\Client\UI\GuiComposer.cs:line 431
   at Vintagestory.GameContent.GuiDialogHandbook.initDetailGui() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 320
   at Vintagestory.GameContent.GuiDialogHandbook.onLeftClickListElement(Int32 index) in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 408
   at Vintagestory.GameContent.GuiElementFlatList.OnMouseUpOnElement(ICoreClientAPI api, MouseEvent args) in VSSurvivalMod\Systems\Handbook\Gui\GuiElementFlatList.cs:line 117
   at Vintagestory.GameContent.GuiElementFlatList.OnMouseUp(ICoreClientAPI api, MouseEvent args) in VSSurvivalMod\Systems\Handbook\Gui\GuiElementFlatList.cs:line 172
   at Vintagestory.API.Client.GuiComposer.OnMouseUp(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 440
   at Vintagestory.API.Client.GuiDialog.OnMouseUp(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 578
   at Vintagestory.Client.NoObf.GuiManager.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 412
   at Vintagestory.Client.NoObf.ClientMain.OnMouseUp(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1862
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonUp(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 209
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.DispatchUpdateFrame()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 312
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3

**Comment by VinterNacht** [comment]
This was a pain, but is resolved.
