### ISSUE TITLE
Causes errors with chisseled schematics 

### ISSUE THREAD

**Issue by WickedSchnitzel** [Aetherial-Labs/Issue-Reporting#19]
[Server Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockEntityMicroBlock.OnTransformed(IWorldAccessor worldAccessor, ITreeAttribute tree, Int32 byDegrees, Dictionary`2 oldBlockIdMapping, Dictionary`2 oldItemIdMapping, Nullable`1 flipAroundAxis) in VSSurvivalMod\Systems\Microblock\BEMicroBlock.cs:line 481
   at Vintagestory.API.Common.BlockSchematic.TransformWhilePacked(IWorldAccessor worldForResolve, EnumOrigin aroundOrigin, Int32 angle, Nullable`1 flipAxis) in VintagestoryApi\Common\Collectible\Block\BlockSchematic.cs:line 925
   at VsVillage.WorldGenVillageStructure.Init(ICoreServerAPI api) in E:\VS Arbeitsdateien\Projekte\VSVillageCoB\src\Systems\WorldGen\VillageStructure.cs:line 50
   at VsVillage.VillageGenerator.initWorldGen() in E:\VS Arbeitsdateien\Projekte\VSVillageCoB\src\Systems\WorldGen\Villagegenerator.cs:line 108
   at Vintagestory.Server.ServerSystemSupplyChunks.LoadWorldgenHandlerAndSpawnChunks() in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 1333
   at Vintagestory.Server.ServerSystemLoadAndSaveGame.OnWorldgenStartup() in VintagestoryLib\Server\Systems\World\LoadThread\LoadSaveGame.cs:line 185
   at Vintagestory.Server.ServerEventManager.TriggerWorldgenStartup() in VintagestoryLib\Server\ServerEventManager.cs:line 481
   
   
   causes errors with chisseled schematics. i needed hours to figure out it was this mod. chisseled schematics won't spawn e.g. from a server pack or when used in the vsvillage mod. will even prevent players from connecting to the server. needs a fix asap

**Comment by VinterNacht** [comment]
The Issue Tracker is for all my mods, can you specify which mod it was?  I'm not seeing it listed in your error report.

**Comment by WickedSchnitzel** [comment]
Golden Combs

Vinter_Nacht ***@***.***> schrieb am Sa., 20. Jan. 2024,
03:37:
